- hosts: all
  become_user: root

  tasks:

     #create groups
     - name: add a group
       name={{ item }}
       state=present
      with_items:
       - demogroup
       - demogroup1
       - demogroup2
      tags: add_new_group

      #add users to specific group
     - name: add users to demogroup
       user:
        name={{ item }}
        state=present
        groups:demogroup
        password=
        shell=/bin/bash
       with_items:
        - demouser
        - demouser1
        - demouser2
       tags:  add_new_user

       #generate public key for users
     - name: generate ssh key for user
       user:
        name={{ item }}
        generate_ssh_key=yes
        ssh_key_bits=4096
        ssh_key_file=.ssh/id_rsa
       with_items:
        - demouser1
       tags: generate_ssh_keys

       #copy public key to user account
     - name: update authorized keys for a user
       authorized_key:
        user:  demouser1
        state: present
        key: "{{lookup('file', '/home/demouser1/.ssh/id_rsa.pub') }}"
       tags: copy_pub_key

       

