#create custom security group
#spin up new ec2 instance
#wait for ssh to become active on new instance
#
#Version 1.0
#
- hosts: localhost

  tasks:

    - name:  Setting up Security/Firewall Group
      ec2_group:
         name:  ansible-client-SG
         description: Rules allowing traffic on port 22 and 80
         region: us-east-1
         rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip:  0.0.0.0/0
            proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip:  0.0.0.0/0
         rules_egress:
          - proto:  all
            cidr_ip:  0.0.0.0/0

     - name:  Provision an EC2 instance
       ec2:
          key_name:  Lab-Main.pem
          region: us-east-1
          instance_type: t2.micro
          image: amzn2-ami-hvm-2.0.20200917.0-x86_64-gp2
          wait: yes
          wait_timeout: 500
          count: 1
          instance_tags:
            Name:  ansible-client-lab
            purpose:  test-ansible
          monitoring: no
          vpc_subnet_id: subnet-09874896af80aec04
          assign_public_ip: yes
          group: ansible-client-SG
        register:  ec2_out


      - name: Wait for SSH to come up
        wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
        with_items: '{{ec2_out.instances}}'
